let timeframe = 30d;
SecurityEvent
| where TimeGenerated > ago(timeframe)
// #############################################################
// ###                    Normalization                      ###
// #############################################################
| project-rename Host = Computer, User = Account
| project TimeGenerated, Host, User, EventID, ParentProcessName, NewProcessName, CommandLine
// #############################################################
// ###                      Filters                          ###
// #############################################################
| where EventID == 4688
| where (ParentProcessName endswith "\\cmd.exe" or ParentProcessName endswith "\\powershell.exe")
| where (
    (CommandLine contains "/c copy" and CommandLine contains "ntds.dit" and CommandLine contains ":\\") or
    (CommandLine contains ".txt" and CommandLine contains "/s" and NewProcessName endswith "\\diskshadow.exe")
)
// #############################################################
// ###                      Stats                            ###
// #############################################################
| summarize count() by Host, User, ParentProcessName,NewProcessName,CommandLine
| order by count_ desc



