let timeframe = 30d;
DeviceEvents
| where Timestamp > ago(timeframe)
// #############################################################
// ###                    Normalization                      ###
// #############################################################
| project-rename Host = DeviceName, User = DeviceUserId
| project Timestamp, Host, User, ActionType, InitiatingProcessFileName, CommandLine, AdditionalInfo
// #############################################################
// ###                      Filters                          ###
// #############################################################
| where ActionType == "CreateProcess"
| where (InitiatingProcessFileName endswith "cmd.exe" or InitiatingProcessFileName endswith "powershell.exe")
| where (
    (CommandLine contains "/c copy" and CommandLine contains "ntds.dit" and CommandLine contains ":\\") or
    (CommandLine contains ".txt" and CommandLine contains "/s" and InitiatingProcessFileName endswith "diskshadow.exe")
)
// #############################################################
// ###                      Stats                            ###
// #############################################################
| summarize count() by Host, User, InitiatingProcessFileName, CommandLine
| order by count_ desc